services:
  - type: web
    name: grocery-bud-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn groceryproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0